import { NextResponse } from "next/server";
import type { ProposedChange } from "@/lib/analysis/types";

export const maxDuration = 60;

function parseRepository(input: string) {
  const match = input.trim().replace(/\.git$/, "").match(/^(?:https?:\/\/github\.com\/)?([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)\/?$/);
  if (!match) throw new Error("Invalid GitHub repository URL");
  return { owner: match[1], repo: match[2] };
}

async function github(path: string, token: string, init: RequestInit = {}) {
  const response = await fetch(`https://api.github.com${path}`, { ...init, headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "Content-Type": "application/json", "User-Agent": "Rivet-Readiness-Orchestrator", ...(init.headers || {}) }, cache: "no-store" });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) {
    if (response.status === 401) throw new Error("GitHub rejected the token. Create a valid fine-grained token with Contents and Pull requests write access.");
    if (response.status === 403) throw new Error("The GitHub token does not have permission to create branches or pull requests for this repository.");
    if (response.status === 422) throw new Error(body.message || "GitHub could not create the branch or pull request.");
    throw new Error(body.message || `GitHub returned ${response.status}`);
  }
  return body;
}

function sanitisePath(path: string) {
  if (!path || path.startsWith("/") || path.includes("..") || path.includes("\\")) throw new Error(`Unsafe proposed path: ${path}`);
  return path;
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const token = String(body.githubToken || "").trim();
    if (!token) throw new Error("A GitHub token is required for repository writes.");
    const { owner, repo } = parseRepository(String(body.repositoryUrl || ""));
    const baseBranch = String(body.baseBranch || "main");
    const changes = (Array.isArray(body.changes) ? body.changes : []) as ProposedChange[];
    if (!changes.length) throw new Error("No approved changes were supplied.");
    if (changes.length > 30) throw new Error("A maximum of 30 files can be written in one Rivet pull request.");

    const baseRef = await github(`/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(baseBranch)}`, token);
    const baseCommit = await github(`/repos/${owner}/${repo}/git/commits/${baseRef.object.sha}`, token);
    const treeEntries = [];
    for (const change of changes) {
      const path = sanitisePath(change.path);
      let content = String(change.content || "");
      if (change.status === "modified") {
        const current = await github(`/repos/${owner}/${repo}/contents/${path.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(baseBranch)}`, token);
        const original = current.encoding === "base64" ? Buffer.from(current.content, "base64").toString("utf8") : "";
        const additions = content.split("\n").filter(Boolean).filter((line) => !original.split(/\r?\n/).includes(line));
        content = `${original.replace(/\s*$/, "")}\n${additions.join("\n")}\n`;
      }
      const blob = await github(`/repos/${owner}/${repo}/git/blobs`, token, { method: "POST", body: JSON.stringify({ content, encoding: "utf-8" }) });
      treeEntries.push({ path, mode: "100644", type: "blob", sha: blob.sha });
    }
    const tree = await github(`/repos/${owner}/${repo}/git/trees`, token, { method: "POST", body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree: treeEntries }) });
    const commit = await github(`/repos/${owner}/${repo}/git/commits`, token, { method: "POST", body: JSON.stringify({ message: "Rivet production-readiness improvements", tree: tree.sha, parents: [baseRef.object.sha] }) });
    const branchName = `rivet/readiness-${Date.now().toString(36)}`;
    await github(`/repos/${owner}/${repo}/git/refs`, token, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: commit.sha }) });
    const pull = await github(`/repos/${owner}/${repo}/pulls`, token, { method: "POST", body: JSON.stringify({ title: String(body.title || "Rivet: Production-readiness improvements"), body: String(body.description || "Generated by Rivet. Human review required."), head: branchName, base: baseBranch, draft: true }) });
    return NextResponse.json({ url: pull.html_url, number: pull.number, branch: branchName, commit: commit.sha });
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Draft pull request creation failed" }, { status: 400 });
  }
}
